# Generated by Django 4.2 on 2023-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_cart_ordered_remove_cart_ordered_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
