"""
Django settings for crepway project.

Generated by 'django-admin startproject' using Django 4.1.3.``


For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os


# Chargement des variables d'environnement à partir du fichier .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = ('YOUR_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False,

ALLOWED_HOSTS = ["'127.0.0.1']



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",
    'accounts',
    'mail',
    'gunicorn',
    'storages',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "crepway.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crepway.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DROPBOX_APP_KEY = ('YOUR_KEYY')
DROPBOX_APP_SECRET = ('YOUR_KEY')
DROPBOX_OAUTH2_TOKEN = ('YOUR_KEY')
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
MEDIA_URL = "Your url Dropbox"
DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'

DROPBOX_STORAGE = {
    'oauth2_token': DROPBOX_OAUTH2_TOKEN,
    'location': MEDIA_URL,
}

# Définir l'emplacement des fichiers médias
MEDIA_ROOT = 'media'


AUTH_USER_MODEL = "accounts.Shopper"
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]
#stripe settings 
STRIPE_PUBLIC_KEY = ('YOUR_KEY')
STRIPE_SECRET_KEY = ('YOUR_KEY')
# Email configuration

EMAIL_BACKEND = ('YOUR_KEY')
EMAIL_HOST = ('YOUR_KEY')
EMAIL_PORT = ('YOUR_KEY')
EMAIL_USE_TLS = ('YOUR_KEY')
EMAIL_HOST_USER = ('YOUR_KEY')
EMAIL_HOST_PASSWORD = ('YOUR_KEY')
MAILJET_API_KEY = ('YOUR_KEY')
MAILJET_API_SECRET = ('YOUR_KEY')
DEFAULT_FROM_EMAIL = ('YOUR_KEY')





